### ISSUE TITLE
Hypothesis testing in function `DMLtest.multiFactor`

### ISSUE THREAD

**Issue by wbvguo** [haowulab/DSS#44]
Dear `DSS` developer,

Thank you for maintaining this tool. 

I recently tried to model the methylation counts of `p` CpG sites using `n` predictors. In the end, it shall yield a `p * (n+1)` coefficient matrix. (the `+1` is for the intercept)

I want to extract the coefficients and significance of each predictor. Instead of using a for loop to iterate through the predictors, I tried `DMLtest.multiFactor(dss_obj, coef= 1:5)`, however the output matrix will have more than `p` rows, suggesting this expression is not valid.  It would be great if the tool could support extracting the coefficients and significance all at once using the such expression.

On the other hand, the `DMLtest.multiFactor()` can test whether a predictors coefficient equals to 0 or not, it would be great if we can also provide a option to test if a handful of predictors' coefficient all equals to 0 (to test the coefficients simultaneously, not individually). This should be useful in some case where we care the the model as a whole.

Thanks,
Wenbin

**Comment by haowulab** [comment]
For your first question, the coefficients need to be tested one by one so you do need a loop. Since in general the number of predictors will be small, I don’t feel this is a big hassle. 

 

For your second question, DMLtest.multiFactor function has a Contrast parameter which allows users to perform any test. 

 

 

 

 

发件人: ***@***.*** ***@***.*** 代表 Wenbin Guo
发送时间: 2024年1月18日 10:23
收件人: haowulab/DSS
抄送: Subscribed
主题: [haowulab/DSS] Hypothesis testing in function `DMLtest.multiFactor` (Issue #44)

 

Dear DSS developer,

Thank you for maintaining this tool.

I recently tried to model the methylation counts of p CpG sites using n predictors. In the end, it shall yield a p x (n+1) coefficient matrix. (the +1 is for the intercept)

I want to extract the coefficients and significance of each predictor. Instead of using a for loop to iterate through the predictors, I tried DMLtest.multiFactor(dss_obj, coef= 1:5), however the output matrix will have more than p rows, suggesting this expression is not valid. It would be great if the tool could support extracting the coefficients and significance all at once using the such expression.

On the other hand, the DMLtest.multiFactor() can test whether a predictors coefficient equals to 0 or not, it would be great if we can also provide a option to test if any of the predictors' coefficient equals to 0 (to test the coefficients simultaneously, not individually). This should be useful in some case where we care the the model as a whole.

Thanks,
Wenbin

**Comment by wbvguo** [comment]
Thank you for the comments! the `Contrast` parameter is useful. 

Previously I did the tests myself by extract the `fit$beta` and `fit$var.beta` from the DSS fit object and for each site `i`, calculate the test statistics
```
t(beta_i) %*% solve(vars_i) %*% beta_i
```

Then used the F-test (or chi-square test) to obtain the p-values

May I ask if this procedure is what `DMLtest.multiFactor` doing?

Thanks,
Wenbin

**Comment by haowulab** [comment]
Yes it’s just an F-test. 

 

发件人: ***@***.*** ***@***.*** 代表 Wenbin Guo
发送时间: 2024年1月23日 11:49
收件人: haowulab/DSS
抄送: Hao Wu; Comment
主题: Re: [haowulab/DSS] Hypothesis testing in function `DMLtest.multiFactor` (Issue #44)

 

Thank you for the comments! the Contrast parameter is useful.

Previously I did the tests myself by extract the fit$beta and fit$var.beta from the DSS fit object and for each site i, calculate the test statistics

t(beta_i) %*% solve(vars_i) %*% beta_i

Then used the F-test (or chi-square test) to obtain the p-values

May I ask if this procedure is what DMLtest.multiFactor doing?

Thanks,
Wenbin

**Comment by wbvguo** [comment]
Got it, thanks! Close this issue now.
